# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: DG | Check if the Data Guard configuration already exists
  shell: |
    set -o pipefail
    ({{ oracle_home }}/bin/dgmgrl -silent / "show database {{ standby_name }}" || true) | awk '/Database Status:/ {getline; print $1}'
  environment:
    ORACLE_HOME: "{{ oracle_home }}"
    ORACLE_SID: "{{ oracle_sid }}"
    PATH: "{{ oracle_home }}/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin"
  become: true
  become_user: "{{ oracle_user }}"
  changed_when: false
  register: current_dg_status
  tags: dg-create

- name: DG | Run Data Guard setup tasks
  when: current_dg_status.stdout | upper != "SUCCESS"
  tags: dg-create
  block:
    - name: DG | Define SQL commands to add standby redo logs
      set_fact:
        sql_for_dg: |
          alter system set dg_broker_start=true sid='*';
          alter system set standby_file_management=auto sid='*';
          -- Oracle's recommendation is to have standby redo logs of equal size and with one more group than the
          -- online redo logs. Consequently, determine the number of online groups vs existing standby groups and
          -- then create standby logs, plus one extra, accordingly.
          -- Reference: https://docs.oracle.com/en/database/oracle/oracle-database/19/sbydb/oracle-data-guard-redo-transport-services.html#GUID-E6EC6104-3C38-482D-B807-A0E84ECFB937
          BEGIN
            FOR c IN (select bytes, thr, (max(cnt_log) - nvl(max(cnt_sby), 0)) diff
                        from (select bytes, thread# thr, count(*) cnt_log, null cnt_sby from v\$log group by bytes, thread#
                              union all
                              select bytes, thread# thr, null cnt_log, count(*) cnt_sby from v\$standby_log group by bytes, thread#
                              )
                        group by bytes, thr
                      ) LOOP
              FOR n IN 1..c.diff + 1 LOOP
                  execute immediate 'alter database add standby logfile thread '||c.thr||' size '||c.bytes;
              END LOOP;
            END LOOP;
          END;
          /

    - name: DG | Enable force logging on the primary
      shell: |
        set -o pipefail
        {{ oracle_home }}/bin/sqlplus -s -L / as sysdba <<EOF
        whenever sqlerror exit failure
        SET serverout ON
        BEGIN
          FOR c IN (select force_logging from v\$database) LOOP
              IF c.force_logging = 'NO' THEN
                execute immediate 'alter database force logging';
                DBMS_OUTPUT.put_line('Enabled database force logging');
              END IF;
          END LOOP;
        END;
        /
        EOF
      environment:
        ORACLE_HOME: "{{ oracle_home }}"
        ORACLE_SID: "{{ oracle_sid }}"
        PATH: "{{ oracle_home }}/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin"
      delegate_to: primary1
      become: true
      become_user: "{{ oracle_user }}"
      register: force_logging
      changed_when: "'Enabled database force logging' in force_logging.stdout"

    - name: DG | Set DG parameters and create standby redo logs on the primary
      shell: |
        set -o pipefail
        {{ oracle_home }}/bin/sqlplus -s -L / as sysdba <<EOF
        whenever sqlerror exit failure
        {{ sql_for_dg }}
        EOF
      environment:
        ORACLE_HOME: "{{ oracle_home }}"
        ORACLE_SID: "{{ oracle_sid }}"
        PATH: "{{ oracle_home }}/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin"
      delegate_to: primary1
      become: true
      become_user: "{{ oracle_user }}"

    - name: DG | Set DG parameters and create standby redo logs on the standby
      shell: |
        set -o pipefail
        {{ oracle_home }}/bin/sqlplus -s -L / as sysdba <<EOF
        whenever sqlerror exit failure
        {{ sql_for_dg }}
        EOF
      environment:
        ORACLE_HOME: "{{ oracle_home }}"
        ORACLE_SID: "{{ oracle_sid }}"
        PATH: "{{ oracle_home }}/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin"
      become: true
      become_user: "{{ oracle_user }}"

    - name: DG | Create the DG setup user on both servers (21c and higher only)
      when: oracle_ver_base | float > 19.3
      block:
        - name: DG | Generate random password for the Data Guard setup user
          set_fact:
            dg_pass: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters,digits') }}0#_"
          no_log: true

        - name: DG | Set the RMAN duplicate username and container string
          set_fact:
            dg_user: "c##toolkit_dg_setup_user"
          when: container_db | bool

        - name: DG | Set the RMAN duplicate username and container string (non-CDB)
          set_fact:
            dg_user: "toolkit_dg_setup_user"
          when: not (container_db | bool)

        - name: DG | Create a temporary user for the Data Guard configuration setup
          shell: |
            set -o pipefail
            {{ oracle_home }}/bin/sqlplus -s -L / as sysdba <<EOF
            whenever sqlerror exit failure
            CREATE USER {{ dg_user }} IDENTIFIED BY "{{ dg_pass }}";
            GRANT sysdg TO {{ dg_user }};
            EOF
          environment:
            ORACLE_HOME: "{{ oracle_home }}"
            ORACLE_SID: "{{ oracle_sid }}"
            PATH: "{{ oracle_home }}/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin"
          delegate_to: primary1
          become: true
          become_user: "{{ oracle_user }}"
          no_log: true

        - name: DG | Create a temporary file for transfer
          tempfile:
            state: file
          register: temp_file

        - name: DG | Fetch password file from primary
          fetch:
            src: "{{ oracle_base }}/dbs/orapw{{ oracle_sid }}"
            dest: "{{ temp_file.path }}"
            flat: true
          delegate_to: primary1

        - name: DG | Copy password file to standby
          copy:
            src: "{{ temp_file.path }}"
            dest: "{{ oracle_base }}/dbs/orapw{{ oracle_sid }}"
            owner: "{{ oracle_user }}"
            group: "{{ oracle_group }}"
            mode: "u=wr,go="

      always:
        - name: DG | Remove temporary file
          file:
            path: "{{ temp_file.path }}"
            state: absent
          when: temp_file.path is defined

    - name: DG | Generate script for creating the Data Guard configuration
      template:
        src: dg-create.j2
        dest: "{{ oracle_home }}/dbs/create_dg_{{ db_name }}.cmd"
        owner: "{{ oracle_user }}"
        group: "{{ oracle_group }}"
        mode: "u=wr,go="
      delegate_to: primary1
      become: true
      become_user: "{{ oracle_user }}"

    - name: DG | Run script to create the Data Guard configuration
      shell: |
        set -o pipefail
        {{ oracle_home }}/bin/dgmgrl <<EOF
        {% if oracle_ver_base | float > 19.3 %}
        connect {{ dg_user }}/"{{ dg_pass }}"
        {% else %}
        connect /
        {% endif %}
        spool "{{ oracle_home }}/dbs/create_dg_{{ db_name }}.log"
        @"{{ oracle_home }}/dbs/create_dg_{{ db_name }}.cmd"
        EOF
      environment:
        ORACLE_HOME: "{{ oracle_home }}"
        ORACLE_SID: "{{ oracle_sid }}"
        PATH: "{{ oracle_home }}/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin"
      delegate_to: primary1
      become: true
      become_user: "{{ oracle_user }}"
      register: dg_create
      no_log: true

    - name: DG | Set other parameters as required for pre-19c standby databases
      shell: |
        set -o pipefail
        {{ oracle_home }}/bin/sqlplus -s -L / as sysdba <<EOF
        whenever sqlerror exit failure
        alter system set archive_lag_target=0 sid='*' scope=both;
        alter system set log_archive_max_processes=4 sid='*' scope=both;
        alter system set log_archive_min_succeed_dest=1 sid='*' scope=both;
        alter system set data_guard_sync_latency=0 sid='*' scope=both;
        EOF
      environment:
        ORACLE_HOME: "{{ oracle_home }}"
        ORACLE_SID: "{{ oracle_sid }}"
        PATH: "{{ oracle_home }}/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin"
      become: true
      become_user: "{{ oracle_user }}"
      when: oracle_ver_base | float <= 18.0

    - name: DG | Gather minimal facts (hostname) for the standby
      setup:
        gather_subset: "min"
      register: standby_facts

    - name: DG | Gather minimal facts (hostname) for the primary
      setup:
        gather_subset: "min"
      delegate_to: primary1
      register: primary_facts

    - name: DG | Manually set the StaticConnectIdentifier parameter (MOS Doc ID 1582927.1)
      shell: |
        set -o pipefail
        STATIC_ID_P="(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST={{ primary_facts.ansible_facts.ansible_hostname }})(PORT={{ listener_port | default(1521, true) }}))(CONNECT_DATA=(SERVICE_NAME={{ db_name }})))"
        STATIC_ID_S="(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST={{ standby_facts.ansible_facts.ansible_hostname }})(PORT={{ listener_port | default(1521, true) }}))(CONNECT_DATA=(SERVICE_NAME={{ standby_name }})))"
        {{ oracle_home }}/bin/dgmgrl / <<EOF
        edit database {{ db_name | lower }}      set property staticConnectidentifier='${STATIC_ID_P}';
        edit database {{ standby_name | lower }} set property staticConnectidentifier='${STATIC_ID_S}';
        EOF
      environment:
        ORACLE_HOME: "{{ oracle_home }}"
        ORACLE_SID: "{{ oracle_sid }}"
        PATH: "{{ oracle_home }}/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin"
      become: true
      become_user: "{{ oracle_user }}"

    - name: DG | Restart standby if required
      shell: |
        set -o pipefail
        {{ oracle_home }}/bin/sqlplus / as sysdba <<EOF
        whenever sqlerror exit failure
        shutdown immediate
        startup mount
        EOF
      environment:
        ORACLE_HOME: "{{ oracle_home }}"
        ORACLE_SID: "{{ oracle_sid }}"
        PATH: "{{ oracle_home }}/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin"
      become: true
      become_user: "{{ oracle_user }}"
      when: "'database instance restart required' in dg_create.stdout"

    - name: DG | Enable standby database after restart to clear warnings
      shell: |
        set -o pipefail
        {{ oracle_home }}/bin/dgmgrl / <<EOF
        enable database {{ standby_name }};
        host sleep 60;
        show database verbose {{ standby_name }};
        EOF
      environment:
        ORACLE_HOME: "{{ oracle_home }}"
        ORACLE_SID: "{{ oracle_sid }}"
        PATH: "{{ oracle_home }}/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin"
      become: true
      become_user: "{{ oracle_user }}"
      when: "'database instance restart required' in dg_create.stdout"

  always:
    - name: DG | Drop the temporary user created for Data Guard setup
      shell: |
        set -o pipefail
        {{ oracle_home }}/bin/sqlplus -s -L / as sysdba <<EOF
        whenever sqlerror exit failure
        DROP USER {{ dg_user }};
        EOF
      environment:
        ORACLE_HOME: "{{ oracle_home }}"
        ORACLE_SID: "{{ oracle_sid }}"
        PATH: "{{ oracle_home }}/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin"
      delegate_to: primary1
      become: true
      become_user: "{{ oracle_user }}"
      when: oracle_ver_base | float > 19.3

- name: DG | Capture Data Guard configuration
  shell: |
    set -o pipefail
    {{ oracle_home }}/bin/dgmgrl / <<EOF
    show configuration verbose;
    EOF
  environment:
    ORACLE_HOME: "{{ oracle_home }}"
    ORACLE_SID: "{{ oracle_sid }}"
    PATH: "{{ oracle_home }}/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin"
  become: true
  become_user: "{{ oracle_user }}"
  changed_when: false
  register: dg_config
  tags: dg-create

- name: DG | Show Data Guard configuration
  debug:
    var: dg_config.stdout_lines
    verbosity: 0
  tags: dg-create
